// https://www.usb.org/sites/default/files/hut1_5.pdf#page=90

hid_usage_table_0x07 = [  // Keyboard/Keypad Page
    // usage_id, usage_name, face
    // 00 Reserved
    ["01", "Keyboard ErrorRollOver"],
    ["02", "Keyboard POSTFail"],
    ["03", "Keyboard ErrorUndefined"],
    ["04", "Keyboard a and A", "aA"],
    ["05", "Keyboard b and B", "bB"],
    ["06", "Keyboard c and C", "cC"],
    ["07", "Keyboard d and D", "dD"],
    ["08", "Keyboard e and E", "eE"],
    ["09", "Keyboard f and F", "fF"],
    ["0A", "Keyboard g and G", "gG"],
    ["0B", "Keyboard h and H", "hH"],
    ["0C", "Keyboard i and I", "iI"],
    ["0D", "Keyboard j and J", "jJ"],
    ["0E", "Keyboard k and K", "kK"],
    ["0F", "Keyboard l and L", "lL"],
    ["10", "Keyboard m and M", "mM"],
    ["11", "Keyboard n and N", "nN"],
    ["12", "Keyboard o and O", "oO"],
    ["13", "Keyboard p and P", "pP"],
    ["14", "Keyboard q and Q", "qQ"],
    ["15", "Keyboard r and R", "rR"],
    ["16", "Keyboard s and S", "sS"],
    ["17", "Keyboard t and T", "tT"],
    ["18", "Keyboard u and U", "uU"],
    ["19", "Keyboard v and V", "vV"],
    ["1A", "Keyboard w and W", "wW"],
    ["1B", "Keyboard x and X", "xX"],
    ["1C", "Keyboard y and Y", "yY"],
    ["1D", "Keyboard z and Z", "zZ"],
    ["1E", "Keyboard 1 and !", "1\""],
    ["1F", "Keyboard 2 and @", "2@"],
    ["20", "Keyboard 3 and #", "3#"],
    ["21", "Keyboard 4 and $", "4$"],
    ["22", "Keyboard 5 and %", "5%"],
    ["23", "Keyboard 6 and ∧", "6^"],
    ["24", "Keyboard 7 and &", "7&"],
    ["25", "Keyboard 8 and *", "8*"],
    ["26", "Keyboard 9 and (", "9("],
    ["27", "Keyboard 0 and )", "0)"],
    ["28", "Keyboard Return (ENTER)", "(ENTER)"],
    ["29", "Keyboard ESCAPE", "(ESC)"],
    ["2A", "Keyboard DELETE (Backspace)", "(Backspace)"],
    ["2B", "Keyboard Tab", "(Tab)"],
    ["2C", "Keyboard Spacebar", " "],
    ["2D", "Keyboard - and (underscore)", "-_"],
    ["2E", "Keyboard = and +", "=+"],
    ["2F", "Keyboard [ and {", "[{"],
    ["30", "Keyboard ] and }", "]}"],
    ["31", "Keyboard \\ and |", "\\|"],
    ["32", "Keyboard Non-US # and ˜", "#~"],
    ["33", "Keyboard ; and :", ";:"],
    ["34", "Keyboard ‘ and “", "‘“"],
    ["35", "Keyboard Grave Accent and Tilde", "`~"],
    ["36", "Keyboard , and <", ",<"],
    ["37", "Keyboard . and >", ".>"],
    ["38", "Keyboard / and ?", "/?"],
    ["39", "Keyboard Caps Lock", "(Caps)"],
    ["3A", "Keyboard F1", "F1"],
    ["3B", "Keyboard F2", "F2"],
    ["3C", "Keyboard F3", "F3"],
    ["3D", "Keyboard F4", "F4"],
    ["3E", "Keyboard F5", "F5"],
    ["3F", "Keyboard F6", "F7"],
    ["40", "Keyboard F7", "F7"],
    ["41", "Keyboard F8", "F8"],
    ["42", "Keyboard F9", "F9"],
    ["43", "Keyboard F10", "F10"],
    ["44", "Keyboard F11", "F11"],
    ["45", "Keyboard F12", "F12"],
    ["46", "Keyboard PrintScreen", "(PrSc)"],
    ["47", "Keyboard Scroll Lock", "(ScLk)"],
    ["48", "Keyboard Pause", "(Pause)"],
    ["49", "Keyboard Insert", "(Ins)"],
    ["4A", "Keyboard Home", "(Home)"],
    ["4B", "Keyboard PageUp", "(PgUp)"],
    ["4C", "Keyboard Delete Forward", "(Del)"],
    ["4D", "Keyboard End", "(End)"],
    ["4E", "Keyboard PageDown", "(PgDn)"],
    ["4F", "Keyboard RightArrow", "(→)"],
    ["50", "Keyboard LeftArrow", "(←)"],
    ["51", "Keyboard DownArrow", "(↓)"],
    ["52", "Keyboard UpArrow", "(↑)"],
    ["53", "Keypad Num Lock and Clear", "(NumLock)"],
    ["54", "Keypad /", "KP-//R5"],
    ["55", "Keypad *", "KP-*/R6"],
    ["56", "Keypad -", "KP--"],
    ["57", "Keypad +", "KP-+"],
    ["58", "Keypad ENTER", "KP-Enter"],
    ["59", "Keypad 1 and End", "KP-1/End/R13"],
    ["5A", "Keypad 2 and Down Arrow", "KP-2/↓/R14"],
    ["5B", "Keypad 3 and PageDn", "KP-3/PgDn/R15"],
    ["5C", "Keypad 4 and Left Arrow", "KP-4/←/R10"],
    ["5D", "Keypad 5", "KP-5//R11"],
    ["5E", "Keypad 6 and Right Arrow", "KP-5/→/R12"],
    ["5F", "Keypad 7 and Home", "KP-7/Home/R7"],
    ["60", "Keypad 8 and Up Arrow", "KP-7/↑/R8"],
    ["61", "Keypad 9 and PageUp", "KP-9/PgUp/R9"],
    ["62", "Keypad 0 and Insert", "KP-0/Ins"],
    ["63", "Keypad . and Delete", "KP-./Del"],
    ["64", "Keyboard Non-US \\ and |", "\\|"],
    ["65", "Keyboard Application", "(Appl)"],
    ["66", "Keyboard Power", "(Power)"],
    ["67", "Keypad =", "KP-=/R4"],
    ["68", "Keyboard F13", "F13"],
    ["69", "Keyboard F14", "F14"],
    ["6A", "Keyboard F15", "F15"],
    ["6B", "Keyboard F16", "F16"],
    ["6C", "Keyboard F17", "F17"],
    ["6D", "Keyboard F18", "F18"],
    ["6E", "Keyboard F19", "F19"],
    ["6F", "Keyboard F20", "F20"],
    ["70", "Keyboard F21", "F21"],
    ["71", "Keyboard F22", "F22"],
    ["72", "Keyboard F23", "F23"],
    ["73", "Keyboard F24", "F24"],
    ["74", "Keyboard Execute", "(Execute)"],
    ["75", "Keyboard Help", "(Help)"],
    ["76", "Keyboard Menu", "(Menu)"],
    ["77", "Keyboard Select", "(Sel) "],
    ["78", "Keyboard Stop", "L1(Stop)"],
    ["79", "Keyboard Again", "L2(Again)"],
    ["7A", "Keyboard Undo", "L4(Undo)"],
    ["7B", "Keyboard Cut", "L10(Cut)"],
    ["7C", "Keyboard Copy", "L6(Copy)"],
    ["7D", "Keyboard Paste", "L8(Paste)"],
    ["7E", "Keyboard Find", "L9(Find)"],
    ["7F", "Keyboard Mute", "(Mute)"],
    ["80", "Keyboard Volume Up", "(Vol+)"],
    ["81", "Keyboard Volume Down", "(Vol-)"],
    ["82", "Keyboard Locking Caps Lock", "(CapsLock)"],
    ["83", "Keyboard Locking Num Lock", "(NumLock)"],
    ["84", "Keyboard Locking Scroll Lock", "(ScrollLock)"],
    ["85", "Keypad Comma", "KP-,"],
    ["86", "Keypad Equal Sign", "KP-=/R4"],
    ["87", "Keyboard International1"],
    ["88", "Keyboard International2"],
    ["89", "Keyboard International3"],
    ["8A", "Keyboard International4"],
    ["8B", "Keyboard International5"],
    ["8C", "Keyboard International6"],
    ["8D", "Keyboard International7"],
    ["8E", "Keyboard International8"],
    ["8F", "Keyboard International9"],
    ["90", "Keyboard LANG1"],
    ["91", "Keyboard LANG2"],
    ["92", "Keyboard LANG3"],
    ["93", "Keyboard LANG4"],
    ["94", "Keyboard LANG5"],
    ["95", "Keyboard LANG6"],
    ["96", "Keyboard LANG7"],
    ["97", "Keyboard LANG8"],
    ["98", "Keyboard LANG9"],
    ["99", "Keyboard Alternate Erase"],
    ["9A", "Keyboard SysReq/Attention"],
    ["9B", "Keyboard Cancel"],
    ["9C", "Keyboard Clear"],
    ["9D", "Keyboard Prior"],
    ["9E", "Keyboard Return"],
    ["9F", "Keyboard Separator"],
    ["A0", "Keyboard Out"],
    ["A1", "Keyboard Oper"],
    ["A2", "Keyboard Clear/Again"],
    ["A3", "Keyboard CrSel/Props"],
    ["A4", "Keyboard ExSel"],
    // A5-AF Reserved
    ["B0", "Keypad 00"],
    ["B1", "Keypad 000"],
    ["B2", "Thousands Separator"],
    ["B3", "Decimal Separator"],
    ["B4", "Currency Unit"],
    ["B5", "Currency Sub-unit"],
    ["B6", "Keypad ("],
    ["B7", "Keypad )"],
    ["B8", "Keypad {"],
    ["B9", "Keypad }"],
    ["BA", "Keypad Tab"],
    ["BB", "Keypad Backspace"],
    ["BC", "Keypad A"],
    ["BD", "Keypad B"],
    ["BE", "Keypad C"],
    ["BF", "Keypad D"],
    ["C0", "Keypad E"],
    ["C1", "Keypad F"],
    ["C2", "Keypad XOR"],
    ["C3", "Keypad ∧"],
    ["C4", "Keypad %"],
    ["C5", "Keypad <"],
    ["C6", "Keypad >"],
    ["C7", "Keypad &"],
    ["C8", "Keypad &&"],
    ["C9", "Keypad |"],
    ["CA", "Keypad ||"],
    ["CB", "Keypad :"],
    ["CC", "Keypad #"],
    ["CD", "Keypad Space"],
    ["CE", "Keypad @"],
    ["CF", "Keypad !"],
    ["D0", "Keypad Memory Store"],
    ["D1", "Keypad Memory Recall"],
    ["D2", "Keypad Memory Clear"],
    ["D3", "Keypad Memory Add"],
    ["D4", "Keypad Memory Subtract"],
    ["D5", "Keypad Memory Multiply"],
    ["D6", "Keypad Memory Divide"],
    ["D7", "Keypad +/-"],
    ["D8", "Keypad Clear"],
    ["D9", "Keypad Clear Entry"],
    ["DA", "Keypad Binary"],
    ["DB", "Keypad Octal"],
    ["DC", "Keypad Decimal"],
    ["DD", "Keypad Hexadecimal"],
    // DE-DF Reserved
    ["E0", "Keyboard LeftControl", "LCtrl"],
    ["E1", "Keyboard LeftShift", "LShift"],
    ["E2", "Keyboard LeftAlt", "LAlt"],
    ["E3", "Keyboard Left GUI", "LGUI"],
    ["E4", "Keyboard RightControl", "RCtrl"],
    ["E5", "Keyboard RightShift", "RShift"],
    ["E6", "Keyboard RightAlt", "RAlt"],
    ["E7", "Keyboard Right GUI", "RGUI"],
]

hid_usage_table_0x0c = [  // Consumer Page
    // usage_id, usage_name, face
    ["CD", "Play/Pause", "Play ⏯️"],
    ["B6", "Scan Previous Track", "Prev ⏮️"],
    ["B5", "Scan Next Track","Next ⏭️"],
    ["E2", "Mute", "Mute 🔇"],
    ["EA", "Volume Decrement", "Vol- 🔉"],
    ["E9", "Volume Increment", "Vol+ 🔊"]
]